apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
  namespace: expense
spec:
  serviceRef:
    name: frontend # route traffic to the awesome-service
    port: 80
  #targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:315069654700:targetgroup/expense-dev-frontend/d5062c216aa44ccb
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:533267158693:targetgroup/expense-dev-frontend/5e6a6798c557131b
## this is the targetgroup arn for expense-dev-frontend